name: Migrate
run-name: Migration started by ${{ github.actor }}
on:
  workflow_dispatch
env:
  WP_BASE_URL: ${{ secrets.WP_BASE_URL }}
  WP_ADMIN_USERNAME: ${{ secrets.WP_ADMIN_USERNAME }}
  WP_ADMIN_PASSWORD: ${{ secrets.WP_ADMIN_PASSWORD }}
jobs:
  Migrate-WordPress-To-Storyblok:
    runs-on: ubuntu-22.04
    steps:
      - name: Print some stuff
        run: |
          echo "Hello world! JSON endpoint: $WP_BASE_URL"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          node --version
      - run: |
          npm install
      - name: Fetch TablePress export
        run: |
          npm run fetch-tablepress-tables
      - run: |
          ls tablepress_export/
