name: Migrate
run-name: Migration started by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      wp_base_url:
        description: 'WordPress Base URL, no trailing slash'
        required: true
        type: string
jobs:
  Migrate-WordPress-To-Storyblok:
    runs-on: ubuntu-22.04
    steps:
      - name: Print some stuff
        run: |
          echo "Hello world! JSON endpoint: ${{ inputs.wp_base_url }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          node --version
      - run: |
          npm install
