name: Migrate
run-name: Migration started by ${{ github.actor }}
on:
  workflow_dispatch
env:
  STORYBLOK_OAUTH_TOKEN: ${{ secrets.STORYBLOK_OAUTH_TOKEN }}
  STORYBLOK_SPACE_ID: ${{ secrets.STORYBLOK_SPACE_ID }}
  STORYBLOK_REGION: ${{ secrets.STORYBLOK_REGION }}
  WP_BASE_URL: ${{ secrets.WP_BASE_URL }}
  WP_ADMIN_USERNAME: ${{ secrets.WP_ADMIN_USERNAME }}
  WP_ADMIN_PASSWORD: ${{ secrets.WP_ADMIN_PASSWORD }}
  RICH_TEXT_COMPONENT_NAME: ${{ secrets.RICH_TEXT_COMPONENT_NAME }}
  EDITORIAL_GUIDELINES_UUID: ${{ secrets.EDITORIAL_GUIDELINES_UUID }}
jobs:
  Migrate-WordPress-To-Storyblok:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          node --version
      - run: |
          npm install
      - name: Fetch TablePress export
        run: |
          npm run fetch-tablepress-tables
      - name: Create migration plan file from secret
        run: |
          echo "${{ secrets.MIGRATION_PLAN_FILE_CONTENTS }}" > migration_plan.csv
      - name: Fetch media JSON
        run: |
          npm run fetch-media-json
      - run: |
          cat media.json
      - run: |
          cat migration_plan.csv
